declare class HttpRequest {
    private url;
    private rawUri;
    private hostname;
    private port;
    private scheme;
    private method;
    private headers;
    private params;
    private body;
    constructor(rawUri: string, hostname: string, port: number, scheme: string, method: string, headers: any, params: any, body: any);
    getUrl(): string;
    getRawUri(): string;
    setRawUri(rawUri: string): void;
    getHostName(): string;
    setHostName(hostname: string): void;
    getPort(): number;
    setPort(port: number): void;
    setScheme(scheme: string): void;
    getScheme(): string;
    getMethod(): string;
    getHeaders(): any;
    getParams(): any;
    setParams(params: any): void;
    getBody(): any;
    setUrl(url: string): void;
    setMethod(method: string): void;
    setHeaders(headers: any): void;
    setBody(body: any): void;
}
export default HttpRequest;
